// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway/controller/component"
	"gateway/controller/config"
	"gateway/controller/infra"
	"gateway/controller/server"
	"gateway/controller/service"
)

// Injectors from wire.go:

func InitializeApp() (*GatewayControllerApp, error) {
	appConfig := config.NewAppConfig()
	valkeyWrap := infra.NewValkeyWrap(appConfig)
	routeParser := component.NewRouteParser()
	routeCache := component.NewUpstreamRouteCache(valkeyWrap, routeParser)
	routeService := service.NewPolicyService(routeCache)
	gatewayControllerServer := server.NewGatewayServer(appConfig, routeService)
	routeMessageHook := component.NewRouteMessageHook(routeCache, valkeyWrap)
	componentSet := component.ComponentSet{
		RouteParser:      routeParser,
		RouteCache:       routeCache,
		RouteMessageHook: routeMessageHook,
	}
	gatewayControllerApp := &GatewayControllerApp{
		Config:      appConfig,
		Server:      gatewayControllerServer,
		Service:     routeService,
		Component:   componentSet,
		GlideValkey: valkeyWrap,
	}
	return gatewayControllerApp, nil
}

// wire.go:

type GatewayControllerApp struct {
	Config      *config.AppConfig
	Server      server.GatewayControllerServer
	Service     service.RouteService
	Component   component.ComponentSet
	GlideValkey *infra.ValkeyWrap
}
