// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway/controller/adapter/config"
	di4 "gateway/controller/adapter/port/in/unix/di"
	"gateway/controller/adapter/port/in/unix/handler"
	"gateway/controller/adapter/port/out/cache"
	"gateway/controller/adapter/port/out/cache/di"
	di2 "gateway/controller/adapter/port/out/di"
	"gateway/controller/application/service"
	di3 "gateway/controller/application/service/di"
)

// Injectors from wire.go:

func InitializeGatewayControllerApp() (*GatewayControllerApp, error) {
	appConfig := config.NewAppConfig()
	valkeyClient := config.NewValkeyClient(appConfig)
	routeValkeyCache := cache.NewRouteValkeyCache(valkeyClient)
	routerCacheDi := di.RouterCacheDi{
		RouteCache: routeValkeyCache,
	}
	adapterPortOutDi := &di2.AdapterPortOutDi{
		RouterCache: routerCacheDi,
	}
	upstreamLookupUseCase := service.NewUpstreamLookupService(routeValkeyCache)
	serviceProvider := &di3.ServiceProvider{
		UpstreamLookupCase: upstreamLookupUseCase,
	}
	upstreamRouter := handler.NewUpStreamHandler(upstreamLookupUseCase)
	unixRouterProvider := &di4.UnixRouterProvider{
		UpStreamRouter: upstreamRouter,
	}
	unixServer := &config.UnixServer{
		UnixRouterProvider: unixRouterProvider,
		AppConfig:          appConfig,
	}
	gatewayControllerApp := &GatewayControllerApp{
		app:                appConfig,
		valkeyClient:       valkeyClient,
		adapterPortOut:     adapterPortOutDi,
		serviceProvider:    serviceProvider,
		unixRouterProvider: unixRouterProvider,
		unixServer:         unixServer,
	}
	return gatewayControllerApp, nil
}

// wire.go:

type GatewayControllerApp struct {
	app                *config.AppConfig
	valkeyClient       config.ValkeyClient
	adapterPortOut     *di2.AdapterPortOutDi
	serviceProvider    *di3.ServiceProvider
	unixRouterProvider *di4.UnixRouterProvider
	unixServer         *config.UnixServer
}
