// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeApp() (*GetwayManager, error) {
	config := NewConfig()
	getwayManager := &GetwayManager{
		Config: config,
	}
	return getwayManager, nil
}

// wire.go:

type GetwayManager struct {
	Config *Config
}
