global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m

  external_labels:
    monitor: 'codelab-monitor'
    query_log_file: query_log_file.log

scrape_configs:
  - job_name: 'monitoring-item'
    scrape_timeout: 10s
    scrape_interval: 10s
    metrics_path: '/metrics'
    scheme: 'http'

    static_configs:
      - targets: ['prometheus:9090', 'node_exporter:9100']
        labels:
          service: 'monitor'


  - job_name: 'my-client'
    scrape_timeout: 10s
    scrape_interval: 10s

    metrics_path: '/_metrics'
    scheme: 'http'
    static_configs:
      - targets: [ 'host.docker.internal:80' ]
        labels:
          service: 'monitor'


  - job_name: 'my-client-2'
    scrape_timeout: 10s
    scrape_interval: 10s

    metrics_path: '/_metrics/control-plane'
    scheme: 'http'
    static_configs:
      - targets: [ 'host.docker.internal:80' ]
        labels:
          service: 'monitor'