// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway/controller/config"
	"gateway/controller/infra"
	"gateway/controller/server"
	"gateway/controller/service"
)

// Injectors from wire.go:

func InitializeApp() (*GatewayControllerApp, error) {
	appConfig := config.NewAppConfig()
	glideValkey := infra.NewGlideValkey(appConfig)
	policyService := service.NewPolicyService(glideValkey)
	gatewayControllerServer := server.NewGatewayServer(appConfig, policyService)
	gatewayControllerApp := &GatewayControllerApp{
		Config:      appConfig,
		Server:      gatewayControllerServer,
		Service:     policyService,
		GlideValkey: glideValkey,
	}
	return gatewayControllerApp, nil
}

// wire.go:

type GatewayControllerApp struct {
	Config      *config.AppConfig
	Server      server.GatewayControllerServer
	Service     service.PolicyService
	GlideValkey *infra.GlideValkey
}
