// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: upstream_lookup.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpstreamLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamLookupRequest) Reset() {
	*x = UpstreamLookupRequest{}
	mi := &file_upstream_lookup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamLookupRequest) ProtoMessage() {}

func (x *UpstreamLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_lookup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamLookupRequest.ProtoReflect.Descriptor instead.
func (*UpstreamLookupRequest) Descriptor() ([]byte, []int) {
	return file_upstream_lookup_proto_rawDescGZIP(), []int{0}
}

func (x *UpstreamLookupRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type UpstreamLookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *UpstreamInfo          `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamLookupResponse) Reset() {
	*x = UpstreamLookupResponse{}
	mi := &file_upstream_lookup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamLookupResponse) ProtoMessage() {}

func (x *UpstreamLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_lookup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamLookupResponse.ProtoReflect.Descriptor instead.
func (*UpstreamLookupResponse) Descriptor() ([]byte, []int) {
	return file_upstream_lookup_proto_rawDescGZIP(), []int{1}
}

func (x *UpstreamLookupResponse) GetInfo() *UpstreamInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *UpstreamLookupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpstreamInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceName     string                 `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	Host            string                 `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`
	Path            string                 `protobuf:"bytes,3,opt,name=Path,proto3" json:"Path,omitempty"`
	OriginalPath    string                 `protobuf:"bytes,4,opt,name=OriginalPath,proto3" json:"OriginalPath,omitempty"`
	Method          string                 `protobuf:"bytes,5,opt,name=Method,proto3" json:"Method,omitempty"`
	RequestTimeout  int64                  `protobuf:"varint,6,opt,name=RequestTimeout,proto3" json:"RequestTimeout,omitempty"`
	ResponseTimeout int64                  `protobuf:"varint,7,opt,name=ResponseTimeout,proto3" json:"ResponseTimeout,omitempty"`
	CacheTimeout    int64                  `protobuf:"varint,8,opt,name=CacheTimeout,proto3" json:"CacheTimeout,omitempty"`
	UserKey         string                 `protobuf:"bytes,9,opt,name=UserKey,proto3" json:"UserKey,omitempty"`
	RateLimitCount  int64                  `protobuf:"varint,10,opt,name=RateLimitCount,proto3" json:"RateLimitCount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpstreamInfo) Reset() {
	*x = UpstreamInfo{}
	mi := &file_upstream_lookup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamInfo) ProtoMessage() {}

func (x *UpstreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_lookup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamInfo.ProtoReflect.Descriptor instead.
func (*UpstreamInfo) Descriptor() ([]byte, []int) {
	return file_upstream_lookup_proto_rawDescGZIP(), []int{2}
}

func (x *UpstreamInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UpstreamInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *UpstreamInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpstreamInfo) GetOriginalPath() string {
	if x != nil {
		return x.OriginalPath
	}
	return ""
}

func (x *UpstreamInfo) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *UpstreamInfo) GetRequestTimeout() int64 {
	if x != nil {
		return x.RequestTimeout
	}
	return 0
}

func (x *UpstreamInfo) GetResponseTimeout() int64 {
	if x != nil {
		return x.ResponseTimeout
	}
	return 0
}

func (x *UpstreamInfo) GetCacheTimeout() int64 {
	if x != nil {
		return x.CacheTimeout
	}
	return 0
}

func (x *UpstreamInfo) GetUserKey() string {
	if x != nil {
		return x.UserKey
	}
	return ""
}

func (x *UpstreamInfo) GetRateLimitCount() int64 {
	if x != nil {
		return x.RateLimitCount
	}
	return 0
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=Detail,proto3" json:"Detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_upstream_lookup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_lookup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_upstream_lookup_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_upstream_lookup_proto protoreflect.FileDescriptor

const file_upstream_lookup_proto_rawDesc = "" +
	"\n" +
	"\x15upstream_lookup.proto\x12\x19adapter.config.proto.grpc\"+\n" +
	"\x15UpstreamLookupRequest\x12\x12\n" +
	"\x04Path\x18\x01 \x01(\tR\x04Path\"k\n" +
	"\x16UpstreamLookupResponse\x12;\n" +
	"\x04Info\x18\x01 \x01(\v2'.adapter.config.proto.grpc.UpstreamInfoR\x04Info\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"\xcc\x02\n" +
	"\fUpstreamInfo\x12 \n" +
	"\vServiceName\x18\x01 \x01(\tR\vServiceName\x12\x12\n" +
	"\x04Host\x18\x02 \x01(\tR\x04Host\x12\x12\n" +
	"\x04Path\x18\x03 \x01(\tR\x04Path\x12\"\n" +
	"\fOriginalPath\x18\x04 \x01(\tR\fOriginalPath\x12\x16\n" +
	"\x06Method\x18\x05 \x01(\tR\x06Method\x12&\n" +
	"\x0eRequestTimeout\x18\x06 \x01(\x03R\x0eRequestTimeout\x12(\n" +
	"\x0fResponseTimeout\x18\a \x01(\x03R\x0fResponseTimeout\x12\"\n" +
	"\fCacheTimeout\x18\b \x01(\x03R\fCacheTimeout\x12\x18\n" +
	"\aUserKey\x18\t \x01(\tR\aUserKey\x12&\n" +
	"\x0eRateLimitCount\x18\n" +
	" \x01(\x03R\x0eRateLimitCount\"A\n" +
	"\rErrorResponse\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x16\n" +
	"\x06Detail\x18\x02 \x01(\tR\x06Detail2\x86\x01\n" +
	"\x15UpstreamLookupService\x12m\n" +
	"\x06Lookup\x120.adapter.config.proto.grpc.UpstreamLookupRequest\x1a1.adapter.config.proto.grpc.UpstreamLookupResponseB.Z,github.com/soafftt/go-api-archway/archway/pbb\x06proto3"

var (
	file_upstream_lookup_proto_rawDescOnce sync.Once
	file_upstream_lookup_proto_rawDescData []byte
)

func file_upstream_lookup_proto_rawDescGZIP() []byte {
	file_upstream_lookup_proto_rawDescOnce.Do(func() {
		file_upstream_lookup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upstream_lookup_proto_rawDesc), len(file_upstream_lookup_proto_rawDesc)))
	})
	return file_upstream_lookup_proto_rawDescData
}

var file_upstream_lookup_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_upstream_lookup_proto_goTypes = []any{
	(*UpstreamLookupRequest)(nil),  // 0: adapter.config.proto.grpc.UpstreamLookupRequest
	(*UpstreamLookupResponse)(nil), // 1: adapter.config.proto.grpc.UpstreamLookupResponse
	(*UpstreamInfo)(nil),           // 2: adapter.config.proto.grpc.UpstreamInfo
	(*ErrorResponse)(nil),          // 3: adapter.config.proto.grpc.ErrorResponse
}
var file_upstream_lookup_proto_depIdxs = []int32{
	2, // 0: adapter.config.proto.grpc.UpstreamLookupResponse.Info:type_name -> adapter.config.proto.grpc.UpstreamInfo
	0, // 1: adapter.config.proto.grpc.UpstreamLookupService.Lookup:input_type -> adapter.config.proto.grpc.UpstreamLookupRequest
	1, // 2: adapter.config.proto.grpc.UpstreamLookupService.Lookup:output_type -> adapter.config.proto.grpc.UpstreamLookupResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_upstream_lookup_proto_init() }
func file_upstream_lookup_proto_init() {
	if File_upstream_lookup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upstream_lookup_proto_rawDesc), len(file_upstream_lookup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_upstream_lookup_proto_goTypes,
		DependencyIndexes: file_upstream_lookup_proto_depIdxs,
		MessageInfos:      file_upstream_lookup_proto_msgTypes,
	}.Build()
	File_upstream_lookup_proto = out.File
	file_upstream_lookup_proto_goTypes = nil
	file_upstream_lookup_proto_depIdxs = nil
}
