syntax = "proto3";

package adapter.config.proto.grpc;
// "github.com/사용자명/프로젝트명/경로" 형태로 적는 것이 관례입니다.
option go_package = "github.com/soafftt/go-api-archway/archway/pb";

service UpstreamLookupService {
    rpc Lookup(UpstreamLookupRequest) returns (UpstreamLookupResponse);
}

message UpstreamLookupRequest {
  string Path = 1;
}

message UpstreamLookupResponse {
  UpstreamInfo Info = 1;
  string Error = 2;
}

message UpstreamInfo {
  string ServiceName = 1;
  string Host = 2;
  string Path = 3;
  string OriginalPath = 4;
  string Method = 5;
  int64 RequestTimeout = 6;
  int64 ResponseTimeout = 7;
  int64 CacheTimeout = 8;
  string UserKey = 9;
  int64 RateLimitCount = 10;
}

message ErrorResponse {
  string Message = 1;
  string Detail = 2;
}