// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: upstream_lookup.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpstreamLookupService_Lookup_FullMethodName = "/adapter.config.proto.grpc.UpstreamLookupService/Lookup"
)

// UpstreamLookupServiceClient is the client API for UpstreamLookupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpstreamLookupServiceClient interface {
	Lookup(ctx context.Context, in *UpstreamLookupRequest, opts ...grpc.CallOption) (*UpstreamLookupResponse, error)
}

type upstreamLookupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpstreamLookupServiceClient(cc grpc.ClientConnInterface) UpstreamLookupServiceClient {
	return &upstreamLookupServiceClient{cc}
}

func (c *upstreamLookupServiceClient) Lookup(ctx context.Context, in *UpstreamLookupRequest, opts ...grpc.CallOption) (*UpstreamLookupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpstreamLookupResponse)
	err := c.cc.Invoke(ctx, UpstreamLookupService_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpstreamLookupServiceServer is the server API for UpstreamLookupService service.
// All implementations must embed UnimplementedUpstreamLookupServiceServer
// for forward compatibility.
type UpstreamLookupServiceServer interface {
	Lookup(context.Context, *UpstreamLookupRequest) (*UpstreamLookupResponse, error)
	mustEmbedUnimplementedUpstreamLookupServiceServer()
}

// UnimplementedUpstreamLookupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpstreamLookupServiceServer struct{}

func (UnimplementedUpstreamLookupServiceServer) Lookup(context.Context, *UpstreamLookupRequest) (*UpstreamLookupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedUpstreamLookupServiceServer) mustEmbedUnimplementedUpstreamLookupServiceServer() {}
func (UnimplementedUpstreamLookupServiceServer) testEmbeddedByValue()                               {}

// UnsafeUpstreamLookupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpstreamLookupServiceServer will
// result in compilation errors.
type UnsafeUpstreamLookupServiceServer interface {
	mustEmbedUnimplementedUpstreamLookupServiceServer()
}

func RegisterUpstreamLookupServiceServer(s grpc.ServiceRegistrar, srv UpstreamLookupServiceServer) {
	// If the following call panics, it indicates UnimplementedUpstreamLookupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpstreamLookupService_ServiceDesc, srv)
}

func _UpstreamLookupService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpstreamLookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpstreamLookupServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpstreamLookupService_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpstreamLookupServiceServer).Lookup(ctx, req.(*UpstreamLookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpstreamLookupService_ServiceDesc is the grpc.ServiceDesc for UpstreamLookupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpstreamLookupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adapter.config.proto.grpc.UpstreamLookupService",
	HandlerType: (*UpstreamLookupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lookup",
			Handler:    _UpstreamLookupService_Lookup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "upstream_lookup.proto",
}
