// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway/adapter/config"
	"gateway/adapter/config/client"
	"gateway/adapter/config/di"
	"gateway/adapter/in"
	di3 "gateway/adapter/in/di"
	"gateway/adapter/in/middleware"
	di2 "gateway/adapter/out/di"
	"gateway/adapter/out/gatewaycontroller"
	"gateway/adapter/out/ratelimit"
	"gateway/application/service"
	di4 "gateway/application/service/di"
)

// Injectors from wire.go:

func InitializeApp() (*GatewayProxyApp, error) {
	appConfig := config.NewAppConfig()
	gatewayControllerClient := client.NewGatewayControllerClient(appConfig)
	adapterConfig := &di.AdapterConfig{
		AppConfig:               appConfig,
		GatewayControllerClient: gatewayControllerClient,
	}
	upstreamLookupPort := gatewaycontroller.NewUpstreamLookup(appConfig, gatewayControllerClient)
	rateLimit := ratelimit.NewRateLimit()
	adapterOutDI := &di2.AdapterOutDI{
		GatewayControllerClient: upstreamLookupPort,
		RateLimiter:             rateLimit,
	}
	upstreamLookupUseCase := service.NewUpstreamLookupService(upstreamLookupPort)
	requestMiddleware := middleware.NewRequestMiddleware(upstreamLookupUseCase, rateLimit)
	middlewareContainer := middleware.NewMiddlewareContainer(requestMiddleware)
	gatewayProxy := in.NewGatewayProxy()
	adapterInDI := &di3.AdapterInDI{
		RequestMiddleware:   requestMiddleware,
		MiddlewareContainer: middlewareContainer,
		GatewayProxy:        gatewayProxy,
	}
	applicationServiceDI := &di4.ApplicationServiceDI{
		UpStreamLookUpUseCase: upstreamLookupUseCase,
	}
	gatewayProxyServer := config.NewGatewayProxyServer(gatewayProxy, middlewareContainer)
	gatewayProxyApp := &GatewayProxyApp{
		adapterConfig:      adapterConfig,
		adapterOutDI:       adapterOutDI,
		adapterInDI:        adapterInDI,
		applicationService: applicationServiceDI,
		proxyServer:        gatewayProxyServer,
	}
	return gatewayProxyApp, nil
}

// wire.go:

type GatewayProxyApp struct {
	adapterConfig      *di.AdapterConfig
	adapterOutDI       *di2.AdapterOutDI
	adapterInDI        *di3.AdapterInDI
	applicationService *di4.ApplicationServiceDI
	proxyServer        *config.GatewayProxyServer
}
