// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway/adapter/config/appconfig"
	"gateway/adapter/config/client"
	"gateway/adapter/config/di"
	"gateway/adapter/config/server"
	"gateway/adapter/in"
	di3 "gateway/adapter/in/di"
	"gateway/adapter/in/middleware"
	"gateway/adapter/out/controlplane"
	di2 "gateway/adapter/out/di"
	"gateway/adapter/out/ratelimit"
	"gateway/application/service"
	di4 "gateway/application/service/di"
)

// Injectors from wire.go:

func InitializeApp() (*GatewayProxyApp, error) {
	config := appconfig.NewConfig()
	httpClient := client.NewHttpClient(config, config)
	grpcClient := client.NewGrpcClient(config, config)
	adapterConfig := &di.AdapterConfig{
		AppConfig:  config,
		HttpClient: httpClient,
		GrpcClient: grpcClient,
	}
	upstreamLookupPort := controlplane.NewUpstreamLookup(config, httpClient)
	upstreamLookupGrpcPort := controlplane.NewUpstreamLookupGrpc(grpcClient)
	rateLimiterPort := ratelimit.NewRateLimit()
	grpcMetricOutPort := controlplane.NewMetricsLookup(grpcClient)
	unixMetricOutPort := controlplane.NewUnixMetricLookup(httpClient)
	adapterOutDI := &di2.AdapterOutDI{
		HttpUpstreamLookupPort: upstreamLookupPort,
		GrpcUpstreamLookupPort: upstreamLookupGrpcPort,
		RateLimiter:            rateLimiterPort,
		GrpcMetricLookupPort:   grpcMetricOutPort,
		UnixMetricLookupPort:   unixMetricOutPort,
	}
	upstreamLookupUseCase := service.NewUpstreamLookupService(upstreamLookupPort, upstreamLookupGrpcPort)
	requestMiddleware := middleware.NewRequestMiddleware(upstreamLookupUseCase, rateLimiterPort)
	metricsMiddleware := middleware.NewMetricsMiddleware(config, grpcMetricOutPort, unixMetricOutPort)
	container := middleware.NewMiddlewareContainer(requestMiddleware, metricsMiddleware)
	gatewayProxy := in.NewGatewayProxy()
	adapterInDI := &di3.AdapterInDI{
		RequestMiddleware:   requestMiddleware,
		MetricsMiddleware:   metricsMiddleware,
		MiddlewareContainer: container,
		GatewayProxy:        gatewayProxy,
	}
	applicationServiceDI := &di4.ApplicationServiceDI{
		UpStreamLookUpUseCase: upstreamLookupUseCase,
	}
	gatewayProxyServer := server.NewGatewayProxyServer(gatewayProxy, container)
	gatewayProxyApp := &GatewayProxyApp{
		adapterConfig:      adapterConfig,
		adapterOutDI:       adapterOutDI,
		adapterInDI:        adapterInDI,
		applicationService: applicationServiceDI,
		proxyServer:        gatewayProxyServer,
	}
	return gatewayProxyApp, nil
}

// wire.go:

type GatewayProxyApp struct {
	adapterConfig      *di.AdapterConfig
	adapterOutDI       *di2.AdapterOutDI
	adapterInDI        *di3.AdapterInDI
	applicationService *di4.ApplicationServiceDI
	proxyServer        *server.GatewayProxyServer
}
