// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeApp() (*GatewayControllerApp, error) {
	config := NewConfig()
	gatewayControllerApp := &GatewayControllerApp{
		Config: config,
	}
	return gatewayControllerApp, nil
}

// wire.go:

type GatewayControllerApp struct {
	Config *Config
}
