package code

const (
	ERROR_NOT_FOUND_PARAMETER       = "ERROR_NOT_FOUND_PARAMETER"
	ERROR_TARGET_URL_PARSING_FAILED = "ERROR_TARGET_URL_PARSING_FAILED"
	NOT_FOUND_RESOURCE              = "NOT_FOUND_RESOURCE"
	NOT_FOUND_UPSTREAM_SERVICE      = "NOT_FOUND_UPSTREAM"
	NOT_FOUND_UPSTREAM_DOMAIN       = "NOT_FOUND_UPSTREAM_DOMAIN"
	NOT_FOUND_UPSTREAM_PATH         = "NOT_FOUND_UPSTREAM_PATH"
	NOT_FOUND_JWT_CODEC             = "NOT_fOUND_JWT_CODEC"
	EXPIRE_JWT                      = "EXPIRE_JWT"         // refresh_token 필요.
	FAIL_AUTHORIZATION              = "FAIL_AUTHORIZATION" // 재로그인이 필요.
)
