// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway/component"
	"gateway/config"
	"gateway/server"
	"gateway/server/middleware"
	"gateway/server/middleware/di"
	"gateway/server/response"
	"gateway/service"
	"net/http"
	"net/http/httputil"
)

// Injectors from wire.go:

func InitializeNewApp() (*GatewayApp, error) {
	appConfig := config.NewAppConfig()
	client := component.NewUnixSocketHTTPClient(appConfig)
	upstreamLookupService := service.NewUpstreamLookupService(appConfig, client)
	jsonErrorResponse := response.NewJsonErrorWriter()
	reverseProxy := server.NewGatewayReverseProxy(jsonErrorResponse)
	upstreamCheckMiddleware := middleware.NewUpstreamCheckMiddleware(upstreamLookupService, jsonErrorResponse)
	authMiddleware := middleware.NewAuthMiddleware()
	middlewareContainers := di.NewMiddlewareContainers(upstreamCheckMiddleware, authMiddleware)
	reverseProxyServer := server.NewReserveProxyServer(reverseProxy, middlewareContainers)
	gatewayApp := &GatewayApp{
		HttpClient:          client,
		Config:              appConfig,
		LookupService:       upstreamLookupService,
		JsonErrorResponse:   jsonErrorResponse,
		ReverseServer:       reverseProxyServer,
		ReverseProxy:        reverseProxy,
		MiddlewareContainer: middlewareContainers,
	}
	return gatewayApp, nil
}

// wire.go:

type GatewayApp struct {
	HttpClient          *http.Client
	Config              *config.AppConfig
	LookupService       service.UpstreamLookupService
	JsonErrorResponse   *response.JsonErrorResponse
	ReverseServer       *server.ReverseProxyServer
	ReverseProxy        *httputil.ReverseProxy
	MiddlewareContainer *di.MiddlewareContainers
}
