// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway/component"
	"gateway/config"
	"gateway/service"
	"net/http"
)

// Injectors from wire.go:

func InitializeNewApp() (*GatewayApp, error) {
	appConfig := config.NewAppConfig()
	client := component.NewHttpClient(appConfig)
	upstreamLookupService := service.NewUpstreamLookupService(appConfig, client)
	gatewayApp := &GatewayApp{
		HttpClient:    client,
		Config:        appConfig,
		LookupService: upstreamLookupService,
	}
	return gatewayApp, nil
}

// wire.go:

type GatewayApp struct {
	HttpClient    *http.Client
	Config        *config.AppConfig
	LookupService service.UpstreamLookupService
}
