// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway/component"
	"gateway/config"
	"net/http"
)

// Injectors from wire.go:

func InitializeNewApp() (*GatewayApp, error) {
	client := component.NewHttpClient()
	appConfig := config.NewAppConfig()
	gatewayApp := &GatewayApp{
		HttpClient: client,
		Config:     appConfig,
	}
	return gatewayApp, nil
}

// wire.go:

type GatewayApp struct {
	HttpClient *http.Client
	Config     *config.AppConfig
}
