// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: matrics/prometheus_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_matrics_prometheus_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matrics_prometheus_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_matrics_prometheus_service_proto_rawDescGZIP(), []int{0}
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_matrics_prometheus_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matrics_prometheus_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_matrics_prometheus_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetricsResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_matrics_prometheus_service_proto protoreflect.FileDescriptor

const file_matrics_prometheus_service_proto_rawDesc = "" +
	"\n" +
	" matrics/prometheus_service.proto\x12\x19adapter.config.proto.grpc\"\x13\n" +
	"\x11GetMetricsRequest\"(\n" +
	"\x12GetMetricsResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data2{\n" +
	"\x0eMetricsService\x12i\n" +
	"\n" +
	"GetMetrics\x12,.adapter.config.proto.grpc.GetMetricsRequest\x1a-.adapter.config.proto.grpc.GetMetricsResponseB.Z,github.com/soafftt/go-api-archway/archway/pbb\x06proto3"

var (
	file_matrics_prometheus_service_proto_rawDescOnce sync.Once
	file_matrics_prometheus_service_proto_rawDescData []byte
)

func file_matrics_prometheus_service_proto_rawDescGZIP() []byte {
	file_matrics_prometheus_service_proto_rawDescOnce.Do(func() {
		file_matrics_prometheus_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matrics_prometheus_service_proto_rawDesc), len(file_matrics_prometheus_service_proto_rawDesc)))
	})
	return file_matrics_prometheus_service_proto_rawDescData
}

var file_matrics_prometheus_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_matrics_prometheus_service_proto_goTypes = []any{
	(*GetMetricsRequest)(nil),  // 0: adapter.config.proto.grpc.GetMetricsRequest
	(*GetMetricsResponse)(nil), // 1: adapter.config.proto.grpc.GetMetricsResponse
}
var file_matrics_prometheus_service_proto_depIdxs = []int32{
	0, // 0: adapter.config.proto.grpc.MetricsService.GetMetrics:input_type -> adapter.config.proto.grpc.GetMetricsRequest
	1, // 1: adapter.config.proto.grpc.MetricsService.GetMetrics:output_type -> adapter.config.proto.grpc.GetMetricsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_matrics_prometheus_service_proto_init() }
func file_matrics_prometheus_service_proto_init() {
	if File_matrics_prometheus_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matrics_prometheus_service_proto_rawDesc), len(file_matrics_prometheus_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matrics_prometheus_service_proto_goTypes,
		DependencyIndexes: file_matrics_prometheus_service_proto_depIdxs,
		MessageInfos:      file_matrics_prometheus_service_proto_msgTypes,
	}.Build()
	File_matrics_prometheus_service_proto = out.File
	file_matrics_prometheus_service_proto_goTypes = nil
	file_matrics_prometheus_service_proto_depIdxs = nil
}
