package example
package main






















































































}	return &service, nil	}		host.InitializeRouter()	for _, host := range service.HostMap {	// 모든 호스트의 라우터 초기화	}		return nil, fmt.Errorf("failed to unmarshal JSON: %w", err)	if err := json.Unmarshal(data, &service); err != nil {	var service upstream.UpStreamService	}		return nil, fmt.Errorf("failed to read file: %w", err)	if err != nil {	data, err := os.ReadFile(filename)func LoadServiceConfig(filename string) (*upstream.UpStreamService, error) {}	}		fmt.Println("✓ Correctly returned nil for non-existent host")	if notFound == nil {	notFound := service.LookupHost("nonexistent.example.com")	}		fmt.Printf("✓ Found: admin.example.com → %s\n", adminHost.Host)	if adminHost != nil {	adminHost := service.LookupHost("admin.example.com")	}		fmt.Printf("✓ Found: api.example.com → %s\n", apiHost.Host)	if apiHost != nil {	apiHost := service.LookupHost("api.example.com")	fmt.Println("=== Host Lookup Test ===")	// LookupHost 테스트	}		fmt.Println()		}			}				fmt.Printf("  ✗ %s → Not Found\n", path)			} else {					path, result.Path, result.RequestTimeout, result.CheckAuthrozation)				fmt.Printf("  ✓ %s → %s (timeout: %dms, auth: %v)\n",			if result != nil {			result := host.LookupPath(path)		for _, path := range testPaths {		fmt.Println("Routing Tests:")		}			"/api/nonexistent",			"/api/health",			"/api/users/john/posts/456",			"/api/users/123",			"/api/users",		testPaths := []string{		// 테스트 라우팅		host.InitializeRouter()		// Router 초기화		fmt.Printf("Routes: %d\n\n", len(host.Request))		fmt.Printf("Upstream Server: %s\n", host.Host)		fmt.Printf("Host Key: %s\n", hostKey)	for hostKey, host := range service.HostMap {	// 각 호스트 정보 출력	fmt.Printf("=== Service: %s ===\n\n", service.Service)	}		log.Fatal(err)	if err != nil {	service, err := LoadServiceConfig("common/dto/upstream/testdata/sample_config.json")	// JSON 파일 로드func main() {)	"gateway/common/dto/upstream"	"os"	"log"	"fmt"	"encoding/json"import (